from __future__ import annotations

import json
import re
from dataclasses import dataclass

from .diagnostics import AnnotationError
from .plan_ir import (
    DecodeArrayPlan,
    DecodeFieldPlan,
    DecodeObjectPlan,
    DecodeOperation,
    DecodePlan,
    ReleaseFieldPlan,
    ReleaseArrayPlan,
    ReleaseOperation,
    ReleasePlan,
)
from .schema_ir import FieldSchema, RecordSchema, RecordShape, SchemaIR, TypeKind


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _identifier(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


@dataclass(frozen=True)
class _Constraint:
    minimum: str | None = None
    maximum: str | None = None
    min_length: int | None = None
    max_length: int | None = None


class CGenerator:
    def __init__(self, schema: SchemaIR, decode_plan: DecodePlan, release_plan: ReleasePlan):
        self.schema = schema
        self.decode_plan = decode_plan
        self.release_plan = release_plan
        self.types = schema.type_map()
        self.records = schema.record_map()
        self.decode_objects = {item.record_id: item for item in decode_plan.objects}
        self.decode_arrays = {item.record_id: item for item in decode_plan.arrays}
        self.release_objects = {item.record_id: item for item in release_plan.objects}
        self.release_arrays = {item.record_id: item for item in release_plan.arrays}

    def generate(self, include: str) -> str:
        self._validate_entrypoints()
        lines = [
            "/* Generated by annotation-parser. Do not edit. */",
            '#include "json_pull.h"',
            '#include "json_any_vec.h"',
            "#include <float.h>",
            "#include <stdbool.h>",
            "#include <stddef.h>",
            "#include <stdint.h>",
            "#include <string.h>",
            f"#include {_c_string(include)}",
            "",
        ]
        lines.extend(self._error_helpers())
        lines.append("")
        for record in self.schema.records:
            lines.append(self._release_prototype(record) + ";")
            lines.append(self._decode_prototype(record) + ";")
        lines.append("")
        for record in self.schema.records:
            lines.extend(self._generate_release(record))
            lines.append("")
        for record in self.schema.records:
            lines.extend(self._generate_decode(record))
            lines.append("")
        lines.extend(self._generate_public_functions())
        return "\n".join(lines).rstrip() + "\n"

    def _helper_suffix(self, record_id: str) -> str:
        return _identifier(record_id.removeprefix("record:"))

    def _release_name(self, record_id: str) -> str:
        return f"jbc_release_{self._helper_suffix(record_id)}"

    def _decode_name(self, record_id: str) -> str:
        return f"jbc_decode_{self._helper_suffix(record_id)}"

    def _release_prototype(self, record: RecordSchema) -> str:
        return f"static void {self._release_name(record.id)}(json_allocator *allocator, {record.c_type} *out)"

    def _decode_prototype(self, record: RecordSchema) -> str:
        return f"static bool {self._decode_name(record.id)}(json_parser *parser, {record.c_type} *out)"

    def _validate_entrypoints(self) -> None:
        cleanup_records = {
            entry.record_id for entry in self.release_plan.entries if entry.record_id is not None
        }
        for function in self.schema.functions:
            if function.role == "jsonDecode":
                if function.return_kind != "bool" or len(function.parameter_types) != 2:
                    raise AnnotationError(
                        "@jsonDecode requires bool function(json_parser *, T *)",
                        function.location,
                    )
                if (
                    function.parameter_kinds[0] != "pointer"
                    or function.parameter_target_names[0] != "json_parser"
                ):
                    raise AnnotationError("the first @jsonDecode parameter must be json_parser *", function.location)
                if function.record_id is None or function.record_id not in self.records:
                    raise AnnotationError("the second @jsonDecode parameter must point to a known structure", function.location)
                if not self.records[function.record_id].public:
                    raise AnnotationError("the @jsonDecode target must have @jsonStruct", function.location)
                if function.record_id not in cleanup_records:
                    raise AnnotationError("each @jsonDecode target requires an @jsonCleanup function", function.location)
            elif function.role == "jsonCleanup":
                if function.return_kind != "void" or len(function.parameter_types) != 2:
                    raise AnnotationError(
                        "@jsonCleanup requires void function(json_allocator *, T *)",
                        function.location,
                    )
                if (
                    function.parameter_kinds[0] != "pointer"
                    or function.parameter_target_names[0] != "json_allocator"
                ):
                    raise AnnotationError("the first @jsonCleanup parameter must be json_allocator *", function.location)
                if function.record_id is None or function.record_id not in self.records:
                    raise AnnotationError("the second @jsonCleanup parameter must point to a known structure", function.location)

    def _error_helpers(self) -> list[str]:
        fields = [field for obj in self.decode_plan.objects for field in obj.fields]
        used_types = {field.value.type_id for field in fields}
        used_types.update(array.element.type_id for array in self.decode_plan.arrays)
        pending = list(used_types)
        while pending:
            item = self.types[pending.pop()]
            if item.target is not None and item.target not in used_types:
                used_types.add(item.target)
                pending.append(item.target)
        needs_context = bool(fields)
        needs_length = any(
            self._counter_limit(array.length_type_id) is not None
            or self._counter_limit(array.capacity_type_id) is not None
            for array in self.decode_plan.arrays
        ) or any(
            field.min_length is not None
            or field.max_length is not None
            or self._counter_limit(field.length_type_id) is not None
            or self.types[field.value.type_id].kind is TypeKind.FIXED_ARRAY
            or (
                self.types[field.value.type_id].kind is TypeKind.STRING
                and self.types[field.value.type_id].capacity is not None
            )
            for field in fields
        )
        needs_number = any(
            field.minimum is not None or field.maximum is not None for field in fields
        ) or any(
            self.types[type_id].kind is TypeKind.FLOAT and self.types[type_id].bits == 32
            for type_id in used_types
        )
        needs_memory = bool(self.decode_plan.arrays) or any(
            self.types[type_id].kind in {TypeKind.POINTER, TypeKind.DYNAMIC_ARRAY}
            or (
                self.types[type_id].kind is TypeKind.STRING
                and self.types[type_id].capacity is None
            )
            for type_id in used_types
        )

        lines: list[str] = []
        context = [
            "static inline void jbc_set_context_error(json_parser *parser, json_error_code code,",
            "                                  const char *key, json_source_location location)",
            "{",
            "    json_error_detail detail = {0};",
            "    detail.other.context.begin = key;",
            "    detail.other.context.end = key + strlen(key);",
            "    json_set_error_at(parser, code, &detail, location);",
            "}",
        ]
        length = [
            "static inline void jbc_set_length_error(json_parser *parser, json_error_code code,",
            "                                 json_range_target target, size_t limit,",
            "                                 json_source_location location)",
            "{",
            "    json_error_detail detail = {0};",
            "    detail.range.target = target;",
            "    detail.range.limit = limit;",
            "    json_set_error_at(parser, code, &detail, location);",
            "}",
        ]
        number = [
            "static inline void jbc_set_number_error(json_parser *parser, json_source_location location,",
            "                                 json_error_span value)",
            "{",
            "    json_error_detail detail = {0};",
            "    detail.range.target = JSON_RANGE_NUMBER_VALUE;",
            "    detail.range.value = value;",
            "    json_set_error_at(parser, JSON_ERROR_RANGE_NUMBER, &detail, location);",
            "}",
        ]
        memory = [
            "static inline void jbc_set_no_memory(json_parser *parser)",
            "{",
            "    json_set_error(parser, JSON_ERROR_OTHER_NO_MEMORY, NULL);",
            "}",
        ]
        for needed, chunk in (
            (needs_context, context),
            (needs_length, length),
            (needs_number, number),
            (needs_memory, memory),
        ):
            if needed:
                if lines:
                    lines.append("")
                lines.extend(chunk)
        return lines

    def _field_expression(self, path: tuple[str, ...], base: str = "out") -> str:
        return base + "->" + ".".join(path)

    def _field_schema(self, record: RecordSchema, path: tuple[str, ...]) -> FieldSchema:
        current = record
        result: FieldSchema | None = None
        for index, name in enumerate(path):
            result = next(field for field in current.fields if field.name == name)
            if index + 1 < len(path):
                current = self.records[result.type_id]
        assert result is not None
        return result

    def _generate_release(self, record: RecordSchema) -> list[str]:
        if record.shape is RecordShape.ARRAY:
            return self._generate_array_release(record, self.release_arrays[record.id])
        plan = self.release_objects[record.id]
        lines = [self._release_prototype(record), "{", "    if (out == NULL) {", "        return;", "    }"]
        for index, field in enumerate(plan.fields):
            expression = self._field_expression(field.path)
            length = self._field_expression(field.length_path) if field.length_path else None
            lines.extend(self._emit_release_value(field.type_id, expression, length, 1, f"r{index}"))
        lines.append("    memset(out, 0, sizeof(*out));")
        lines.append("}")
        return lines

    def _generate_array_release(
        self, record: RecordSchema, plan: ReleaseArrayPlan
    ) -> list[str]:
        elems = self._field_expression(plan.elems_path)
        count_path = plan.length_path or plan.capacity_path
        lines = [
            self._release_prototype(record),
            "{",
            "    if (out == NULL) {",
            "        return;",
            "    }",
        ]
        if plan.release_elements:
            assert count_path is not None
            count = self._field_expression(count_path)
            lines.extend([
                f"    if ({elems} != NULL) {{",
                f"        for (size_t r0 = 0; r0 < (size_t)({count}); ++r0) {{",
            ])
            lines.extend(
                self._emit_release_value(
                    plan.element_type_id, f"({elems})[r0]", None, 3, "r0e"
                )
            )
            lines.append("        }")
            lines.append("    }")
        lines.extend([
            f"    if ({elems} != NULL) {{",
            f"        allocator->free({elems});",
            "    }",
            "    memset(out, 0, sizeof(*out));",
            "}",
        ])
        return lines

    def _emit_release_value(
        self,
        type_id: str,
        expression: str,
        length_expression: str | None,
        indent: int,
        variable: str,
        allocator: str = "allocator",
    ) -> list[str]:
        item = self.types[type_id]
        pad = "    " * indent
        lines: list[str] = []
        if item.kind is TypeKind.STRING and item.capacity is None:
            lines.extend([
                f"{pad}if ({expression} != NULL) {{",
                f"{pad}    {allocator}->free({expression});",
                f"{pad}    {expression} = NULL;",
                f"{pad}}}",
            ])
        elif item.kind is TypeKind.RECORD:
            lines.append(f"{pad}{self._release_name(item.id)}({allocator}, &({expression}));")
        elif item.kind is TypeKind.POINTER and item.target is not None:
            lines.append(f"{pad}if ({expression} != NULL) {{")
            lines.extend(self._emit_release_value(item.target, f"*({expression})", None, indent + 1, variable + "p", allocator))
            lines.extend([
                f"{pad}    {allocator}->free({expression});",
                f"{pad}    {expression} = NULL;",
                f"{pad}}}",
            ])
        elif item.kind in {TypeKind.DYNAMIC_ARRAY, TypeKind.FIXED_ARRAY} and item.target is not None:
            if item.kind is TypeKind.DYNAMIC_ARRAY:
                assert length_expression is not None
                count = length_expression
            elif length_expression is not None:
                count = length_expression
            else:
                count = str(item.capacity or 0)
            lines.append(f"{pad}for (size_t {variable} = 0; {variable} < (size_t)({count}); ++{variable}) {{")
            lines.extend(
                self._emit_release_value(item.target, f"({expression})[{variable}]", None, indent + 1, variable + "e", allocator)
            )
            lines.append(f"{pad}}}")
            if item.kind is TypeKind.DYNAMIC_ARRAY:
                lines.extend([
                    f"{pad}if ({expression} != NULL) {{",
                    f"{pad}    {allocator}->free({expression});",
                    f"{pad}    {expression} = NULL;",
                    f"{pad}}}",
                ])
            if length_expression is not None:
                lines.append(f"{pad}{length_expression} = 0;")
        return lines

    def _generate_decode(self, record: RecordSchema) -> list[str]:
        if record.shape is RecordShape.ARRAY:
            return self._generate_array_decode(record, self.decode_arrays[record.id])
        plan = self.decode_objects[record.id]
        count = max(1, len(plan.fields))
        lines = [
            self._decode_prototype(record),
            "{",
            f"    unsigned char seen[{count}] = {{0}};",
            "    json_source_location object_end_location = {0};",
            "    if (!json_object_begin(parser)) {",
            "        goto fail;",
            "    }",
            "    if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACE) {",
            "        object_end_location = json_peek_token(parser)->location;",
            "        if (!json_object_try_end(parser)) {",
            "            goto fail;",
            "        }",
            "        goto object_done;",
            "    }",
            "    while (true) {",
            "        json_source_location key_location = json_peek_token(parser)->location;",
            "        json_string key = {0};",
            "        int field_index = -1;",
            "        if (!json_decode_string(parser, &key)) {",
            "            goto fail;",
            "        }",
            "        if (!json_consume_colon(parser)) {",
            "            json_free_string(parser->allocator, &key);",
            "            goto fail;",
            "        }",
        ]
        for index, field in enumerate(plan.fields):
            comparisons = " || ".join(
                f"json_slice_eq_str(&key.text, {_c_string(key)})" for key in field.keys
            )
            keyword = "if" if index == 0 else "else if"
            lines.append(f"        {keyword} ({comparisons}) {{")
            lines.append(f"            field_index = {field.seen_index};")
            lines.append("        }")
        lines.extend([
            "        json_free_string(parser->allocator, &key);",
            "        switch (field_index) {",
        ])
        for field in plan.fields:
            lines.extend(self._generate_field_case(record, field))
        lines.extend([
            "        default:",
            "            if (!json_skip_value(parser)) {",
            "                goto fail;",
            "            }",
            "            break;",
            "        }",
            "        if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACE) {",
            "            object_end_location = json_peek_token(parser)->location;",
            "            if (!json_object_try_end(parser)) {",
            "                goto fail;",
            "            }",
            "            break;",
            "        }",
            "        if (!json_consume_comma(parser)) {",
            "            goto fail;",
            "        }",
            "    }",
            "object_done:",
        ])
        for field in plan.fields:
            if field.required:
                lines.extend([
                    f"    if (!seen[{field.seen_index}]) {{",
                    f"        jbc_set_context_error(parser, JSON_ERROR_OTHER_MISSING_REQUIRED_KEY, {_c_string(field.keys[0])}, object_end_location);",
                    "        goto fail;",
                    "    }",
                ])
        lines.extend([
            "    return true;",
            "fail:",
            f"    {self._release_name(record.id)}(parser->allocator, out);",
            "    return false;",
            "}",
        ])
        return lines

    def _counter_limit(self, type_id: str | None) -> int | None:
        if type_id is None:
            return None
        item = self.types[type_id]
        assert item.kind is TypeKind.INTEGER and not item.signed
        bits = item.bits or 64
        # The supported target is LP64, so a 64-bit unsigned counter can hold size_t.
        return (1 << bits) - 1 if bits < 64 else None

    def _emit_counter_check(
        self,
        value: str,
        type_id: str | None,
        location: str,
        fail_label: str,
        indent: int,
    ) -> list[str]:
        limit = self._counter_limit(type_id)
        if limit is None:
            return []
        pad = "    " * indent
        return [
            f"{pad}if ({value} > (size_t){limit}) {{",
            f"{pad}    jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {limit}, {location});",
            f"{pad}    goto {fail_label};",
            f"{pad}}}",
        ]

    def _generate_array_decode(
        self, record: RecordSchema, plan: DecodeArrayPlan
    ) -> list[str]:
        target = self.types[plan.element.type_id]
        elems = self._field_expression(plan.elems_path)
        length = self._field_expression(plan.length_path) if plan.length_path else None
        capacity = self._field_expression(plan.capacity_path) if plan.capacity_path else None
        lines = [
            self._decode_prototype(record),
            "{",
            "    json_any_vec array_vec = {0};",
            "    size_t array_count = 0;",
            f"    {elems} = NULL;",
        ]
        if self._counter_limit(plan.capacity_type_id) is not None:
            lines.insert(4, "    json_source_location array_location = json_peek_token(parser)->location;")
        if length is not None:
            lines.append(f"    {length} = 0;")
        if capacity is not None:
            lines.append(f"    {capacity} = 0;")
        lines.extend([
            "    if (!json_array_begin(parser)) {",
            "        goto fail;",
            "    }",
            "    if (!json_array_try_end(parser)) {",
            "        while (true) {",
        ])
        # Reject before decoding the first element that cannot be represented by len.
        limit = self._counter_limit(plan.length_type_id)
        if limit is not None:
            lines.extend([
                f"            if (array_count >= (size_t){limit}) {{",
                f"                jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {limit}, json_peek_token(parser)->location);",
                "                goto array_fail;",
                "            }",
            ])
        lines.extend([
            f"            if (!json_any_vec_reserve(parser->allocator, &array_vec, sizeof({target.c_type}))) {{",
            "                jbc_set_no_memory(parser);",
            "                goto array_fail;",
            "            }",
            f"            {target.c_type} *array_element = ({target.c_type} *)(array_vec.data + array_vec.byte_len);",
            f"            array_vec.byte_len += sizeof({target.c_type});",
            "            ++array_count;",
        ])
        lines.extend(
            self._emit_decode_value(
                plan.element.type_id,
                "*array_element",
                None,
                _Constraint(),
                "array_fail",
                3,
                "array_element",
            )
        )
        lines.extend([
            "            if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACKET) {",
            "                if (!json_array_try_end(parser)) goto array_fail;",
            "                break;",
            "            }",
            "            if (!json_consume_comma(parser)) goto array_fail;",
            "        }",
            "    }",
        ])
        if capacity is not None:
            lines.append(
                f"    size_t array_capacity = array_vec.byte_cap / sizeof({target.c_type});"
            )
            lines.extend(
                self._emit_counter_check(
                    "array_capacity", plan.capacity_type_id, "array_location", "array_fail", 1
                )
            )
        lines.append(f"    {elems} = ({target.c_type} *)array_vec.data;")
        if length is not None:
            field_type = self._field_schema(record, plan.length_path).c_type
            lines.append(f"    {length} = ({field_type})array_count;")
        if capacity is not None:
            field_type = self._field_schema(record, plan.capacity_path).c_type
            lines.append(f"    {capacity} = ({field_type})array_capacity;")
        lines.extend([
            "    array_vec.data = NULL;",
            "    return true;",
            "array_fail:",
            "    for (size_t array_cleanup = 0; array_cleanup < array_count; ++array_cleanup) {",
        ])
        lines.extend(
            self._emit_release_value(
                plan.element.type_id,
                f"(({target.c_type} *)array_vec.data)[array_cleanup]",
                None,
                2,
                "array_cleanup_element",
                "parser->allocator",
            )
        )
        lines.extend([
            "    }",
            "    if (array_vec.data != NULL) parser->allocator->free(array_vec.data);",
            "fail:",
            f"    {self._release_name(record.id)}(parser->allocator, out);",
            "    return false;",
            "}",
        ])
        return lines

    def _generate_field_case(self, record: RecordSchema, field: DecodeFieldPlan) -> list[str]:
        index = field.seen_index
        expression = self._field_expression(field.path)
        length = self._field_expression(field.length_path) if field.length_path else None
        constraint = _Constraint(field.minimum, field.maximum, field.min_length, field.max_length)
        lines = [f"        case {index}: {{"]
        lines.extend([
            f"            if (seen[{index}]) {{",
            f"                jbc_set_context_error(parser, JSON_ERROR_OTHER_DUPLICATE_KEY, {_c_string(field.keys[0])}, key_location);",
            "                goto fail;",
            "            }",
            f"            seen[{index}] = 1;",
        ])
        if field.required:
            lines.extend([
                "            if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {",
                f"                jbc_set_context_error(parser, JSON_ERROR_OTHER_NULL_REQUIRED_VALUE, {_c_string(field.keys[0])}, json_peek_token(parser)->location);",
                "                goto fail;",
                "            }",
            ])
        lines.extend(
            self._emit_decode_value(
                field.value.type_id,
                expression,
                length,
                constraint,
                "fail",
                3,
                f"f{index}",
                field.length_type_id,
            )
        )
        lines.extend(["            break;", "        }"])
        return lines

    def _emit_decode_value(
        self,
        type_id: str,
        expression: str,
        length_expression: str | None,
        constraint: _Constraint,
        fail_label: str,
        indent: int,
        variable: str,
        length_type_id: str | None = None,
    ) -> list[str]:
        item = self.types[type_id]
        pad = "    " * indent
        lines: list[str] = []
        if item.kind is TypeKind.BOOL:
            lines.append(f"{pad}if (!json_decode_bool(parser, &({expression}))) goto {fail_label};")
        elif item.kind in {TypeKind.INTEGER, TypeKind.ENUM}:
            bits = item.bits or 32
            signed = bool(item.signed)
            function = f"json_decode_{'i' if signed else 'u'}{bits}"
            needs_location = constraint.minimum is not None or constraint.maximum is not None
            if item.kind is TypeKind.ENUM:
                temp_type = f"{'int' if signed else 'uint'}{bits}_t"
                lines.append(f"{pad}{temp_type} {variable}_number = 0;")
                if needs_location:
                    lines.append(f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
                    lines.append(f"{pad}json_error_span {variable}_span = {{json_peek_token(parser)->str.begin, json_peek_token(parser)->str.end}};")
                lines.append(f"{pad}if (!{function}(parser, &{variable}_number)) goto {fail_label};")
                lines.append(f"{pad}{expression} = ({item.c_type}){variable}_number;")
            else:
                if needs_location:
                    lines.append(f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
                    lines.append(f"{pad}json_error_span {variable}_span = {{json_peek_token(parser)->str.begin, json_peek_token(parser)->str.end}};")
                lines.append(f"{pad}if (!{function}(parser, &({expression}))) goto {fail_label};")
            lines.extend(self._emit_number_constraints(expression, constraint, variable, fail_label, indent))
        elif item.kind is TypeKind.FLOAT:
            needs_location = item.bits == 32 or constraint.minimum is not None or constraint.maximum is not None
            if needs_location:
                lines.append(f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
                lines.append(f"{pad}json_error_span {variable}_span = {{json_peek_token(parser)->str.begin, json_peek_token(parser)->str.end}};")
            if item.bits == 32:
                lines.append(f"{pad}double {variable}_number = 0.0;")
                lines.append(f"{pad}if (!json_decode_f64(parser, &{variable}_number)) goto {fail_label};")
                lines.append(f"{pad}if ({variable}_number < -FLT_MAX || {variable}_number > FLT_MAX) {{")
                lines.append(f"{pad}    jbc_set_number_error(parser, {variable}_location, {variable}_span);")
                lines.append(f"{pad}    goto {fail_label};")
                lines.append(f"{pad}}}")
                lines.append(f"{pad}{expression} = (float){variable}_number;")
            else:
                lines.append(f"{pad}if (!json_decode_f64(parser, &({expression}))) goto {fail_label};")
            lines.extend(self._emit_number_constraints(expression, constraint, variable, fail_label, indent))
        elif item.kind is TypeKind.STRING:
            lines.extend(self._emit_string(item, expression, constraint, fail_label, indent, variable))
        elif item.kind is TypeKind.RECORD:
            lines.append(f"{pad}if (!{self._decode_name(item.id)}(parser, &({expression}))) goto {fail_label};")
        elif item.kind is TypeKind.POINTER and item.target is not None:
            lines.extend(self._emit_pointer(item, expression, fail_label, indent, variable))
        elif item.kind is TypeKind.FIXED_ARRAY and item.target is not None:
            lines.extend(
                self._emit_fixed_array(
                    item,
                    expression,
                    length_expression,
                    length_type_id,
                    constraint,
                    fail_label,
                    indent,
                    variable,
                )
            )
        elif item.kind is TypeKind.DYNAMIC_ARRAY and item.target is not None:
            assert length_expression is not None
            lines.extend(
                self._emit_dynamic_array(
                    item,
                    expression,
                    length_expression,
                    length_type_id,
                    constraint,
                    fail_label,
                    indent,
                    variable,
                )
            )
        else:
            raise AssertionError(f"unsupported decode type {item}")
        return lines

    def _emit_number_constraints(
        self,
        expression: str,
        constraint: _Constraint,
        variable: str,
        fail_label: str,
        indent: int,
    ) -> list[str]:
        conditions = []
        if constraint.minimum is not None:
            conditions.append(f"({expression}) < ({constraint.minimum})")
        if constraint.maximum is not None:
            conditions.append(f"({expression}) > ({constraint.maximum})")
        if not conditions:
            return []
        pad = "    " * indent
        return [
            f"{pad}if ({' || '.join(conditions)}) {{",
            f"{pad}    jbc_set_number_error(parser, {variable}_location, {variable}_span);",
            f"{pad}    goto {fail_label};",
            f"{pad}}}",
        ]

    def _emit_string(self, item, expression, constraint, fail_label, indent, variable) -> list[str]:
        pad = "    " * indent
        lines: list[str] = []
        nullable = item.capacity is None
        if nullable:
            lines.extend([
                f"{pad}if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {{",
                f"{pad}    if (!json_decode_null(parser)) goto {fail_label};",
                f"{pad}}} else {{",
            ])
            body_indent = indent + 1
        else:
            body_indent = indent
        body = "    " * body_indent
        lines.extend([
            f"{body}json_source_location {variable}_location = json_peek_token(parser)->location;",
            f"{body}json_string {variable}_string = {{0}};",
            f"{body}if (!json_decode_string(parser, &{variable}_string)) goto {fail_label};",
            f"{body}size_t {variable}_length = json_slice_len(&{variable}_string.text);",
            f"{body}if (memchr({variable}_string.text.begin, '\\0', {variable}_length) != NULL) {{",
            f"{body}    json_free_string(parser->allocator, &{variable}_string);",
            f"{body}    json_set_error_at(parser, JSON_ERROR_OTHER_EMBEDDED_NUL, NULL, {variable}_location);",
            f"{body}    goto {fail_label};",
            f"{body}}}",
        ])
        limits: list[tuple[str, int]] = []
        if constraint.min_length is not None:
            limits.append((f"{variable}_length < {constraint.min_length}", constraint.min_length))
        if constraint.max_length is not None:
            limits.append((f"{variable}_length > {constraint.max_length}", constraint.max_length))
        if item.capacity is not None:
            limits.append((f"{variable}_length >= {item.capacity}", max(0, item.capacity - 1)))
        for condition, limit in limits:
            lines.extend([
                f"{body}if ({condition}) {{",
                f"{body}    json_free_string(parser->allocator, &{variable}_string);",
                f"{body}    jbc_set_length_error(parser, JSON_ERROR_RANGE_STRING_LENGTH, JSON_RANGE_STRING_LENGTH, {limit}, {variable}_location);",
                f"{body}    goto {fail_label};",
                f"{body}}}",
            ])
        if item.capacity is None:
            lines.extend([
                f"{body}json_error_code {variable}_code = json_string_into_owned_c_str(parser->allocator, &{variable}_string, &({expression}));",
                f"{body}if ({variable}_code != JSON_ERROR_NONE) {{",
                f"{body}    json_free_string(parser->allocator, &{variable}_string);",
                f"{body}    json_set_error_at(parser, {variable}_code, NULL, {variable}_location);",
                f"{body}    goto {fail_label};",
                f"{body}}}",
            ])
        else:
            lines.extend([
                f"{body}size_t {variable}_written = 0;",
                f"{body}(void)json_slice_write_to_buf(&{variable}_string.text, {expression}, {item.capacity}, &{variable}_written);",
                f"{body}json_free_string(parser->allocator, &{variable}_string);",
            ])
        if nullable:
            lines.append(f"{pad}}}")
        return lines

    def _emit_pointer(self, item, expression, fail_label, indent, variable) -> list[str]:
        pad = "    " * indent
        pointer_fail = f"{variable}_pointer_fail"
        pointer_done = f"{variable}_pointer_done"
        target = self.types[item.target]
        lines = [
            f"{pad}if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {{",
            f"{pad}    if (!json_decode_null(parser)) goto {fail_label};",
            f"{pad}}} else {{",
        ]
        if target.kind is TypeKind.RECORD:
            target_record = self.records[target.id]
            token = (
                "JSON_TOKEN_LBRACKET"
                if target_record.shape is RecordShape.ARRAY
                else "JSON_TOKEN_LBRACE"
            )
            expected = (
                "JSON_EXPECTED_ARRAY"
                if target_record.shape is RecordShape.ARRAY
                else "JSON_EXPECTED_OBJECT"
            )
            lines.extend([
                f"{pad}    if (json_peek_token(parser)->kind != {token}) {{",
                f"{pad}        json_error_detail {variable}_type_error = {{0}};",
                f"{pad}        {variable}_type_error.type.expected = {expected};",
                f"{pad}        {variable}_type_error.type.actual = json_peek_token(parser)->kind;",
                f"{pad}        json_set_error(parser, JSON_ERROR_TYPE_MISMATCH, &{variable}_type_error);",
                f"{pad}        goto {fail_label};",
                f"{pad}    }}",
            ])
        lines.extend([
            f"{pad}    {expression} = ({target.c_type} *)parser->allocator->malloc(sizeof(*({expression})));",
            f"{pad}    if ({expression} == NULL) {{",
            f"{pad}        jbc_set_no_memory(parser);",
            f"{pad}        goto {fail_label};",
            f"{pad}    }}",
            f"{pad}    memset({expression}, 0, sizeof(*({expression})));",
        ])
        lines.extend(self._emit_decode_value(item.target, f"*({expression})", None, _Constraint(), pointer_fail, indent + 1, variable + "p"))
        lines.extend([
            f"{pad}    goto {pointer_done};",
            f"{pointer_fail}:",
        ])
        lines.extend(self._emit_release_value(item.target, f"*({expression})", None, indent + 1, variable + "pr", "parser->allocator"))
        lines.extend([
            f"{pad}    parser->allocator->free({expression});",
            f"{pad}    {expression} = NULL;",
            f"{pad}    goto {fail_label};",
            f"{pointer_done}: ;",
            f"{pad}}}",
        ])
        return lines

    def _emit_array_length_checks(
        self, count: str, constraint: _Constraint, fail_label: str, indent: int, variable: str
    ) -> list[str]:
        pad = "    " * indent
        lines: list[str] = []
        for operator, limit in (("<", constraint.min_length), (">", constraint.max_length)):
            if limit is None:
                continue
            lines.extend([
                f"{pad}if ({count} {operator} {limit}) {{",
                f"{pad}    jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {limit}, {variable}_location);",
                f"{pad}    goto {fail_label};",
                f"{pad}}}",
            ])
        return lines

    def _emit_fixed_array(
        self,
        item,
        expression,
        length_expression,
        length_type_id,
        constraint,
        fail_label,
        indent,
        variable,
    ):
        pad = "    " * indent
        capacity = item.capacity or 0
        lines = [f"{pad}size_t {variable}_count = 0;"]
        if constraint.min_length is not None or constraint.max_length is not None:
            lines.insert(0, f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
        if length_expression:
            lines.append(f"{pad}{length_expression} = 0;")
        lines.extend([
            f"{pad}if (!json_array_begin(parser)) goto {fail_label};",
            f"{pad}if (!json_array_try_end(parser)) {{",
            f"{pad}while (true) {{",
            f"{pad}    if ({variable}_count >= {capacity}) {{",
            f"{pad}        jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {capacity}, json_peek_token(parser)->location);",
            f"{pad}        goto {fail_label};",
            f"{pad}    }}",
        ])
        if constraint.max_length is not None and constraint.max_length < capacity:
            lines.extend([
                f"{pad}    if ({variable}_count >= {constraint.max_length}) {{",
                f"{pad}        jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {constraint.max_length}, json_peek_token(parser)->location);",
                f"{pad}        goto {fail_label};",
                f"{pad}    }}",
            ])
        length_limit = self._counter_limit(length_type_id)
        if length_limit is not None:
            lines.extend([
                f"{pad}    if ({variable}_count >= (size_t){length_limit}) {{",
                f"{pad}        jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {length_limit}, json_peek_token(parser)->location);",
                f"{pad}        goto {fail_label};",
                f"{pad}    }}",
            ])
        if length_expression:
            # Include the zero-initialized current slot in rollback if element decoding fails.
            lines.extend([
                f"{pad}    ++{variable}_count;",
                f"{pad}    {length_expression} = {variable}_count;",
            ])
        lines.extend(
            self._emit_decode_value(
                item.target,
                (
                    f"({expression})[{variable}_count - 1]"
                    if length_expression
                    else f"({expression})[{variable}_count]"
                ),
                None,
                _Constraint(),
                fail_label,
                indent + 1,
                variable + "e",
            )
        )
        if not length_expression:
            lines.append(f"{pad}    ++{variable}_count;")
        lines.extend([
            f"{pad}    if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACKET) {{",
            f"{pad}        if (!json_array_try_end(parser)) goto {fail_label};",
            f"{pad}        break;",
            f"{pad}    }}",
            f"{pad}    if (!json_consume_comma(parser)) goto {fail_label};",
            f"{pad}}}",
            f"{pad}}}",
        ])
        lines.extend(self._emit_array_length_checks(f"{variable}_count", constraint, fail_label, indent, variable))
        return lines

    def _emit_dynamic_array(
        self,
        item,
        expression,
        length_expression,
        length_type_id,
        constraint,
        fail_label,
        indent,
        variable,
    ):
        pad = "    " * indent
        target = self.types[item.target]
        array_fail = f"{variable}_array_fail"
        array_done = f"{variable}_array_done"
        lines = [
            f"{pad}{expression} = NULL;",
            f"{pad}{length_expression} = 0;",
            f"{pad}if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {{",
            f"{pad}    if (!json_decode_null(parser)) goto {fail_label};",
            f"{pad}}} else {{",
            f"{pad}    json_any_vec {variable}_vec = {{0}};",
            f"{pad}    size_t {variable}_count = 0;",
            f"{pad}    if (!json_array_begin(parser)) goto {array_fail};",
            f"{pad}    if (!json_array_try_end(parser)) {{",
            f"{pad}    while (true) {{",
        ]
        if constraint.min_length is not None or constraint.max_length is not None:
            lines.insert(6, f"{pad}    json_source_location {variable}_location = json_peek_token(parser)->location;")
        if constraint.max_length is not None:
            lines.extend([
                f"{pad}        if ({variable}_count >= {constraint.max_length}) {{",
                f"{pad}            jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {constraint.max_length}, json_peek_token(parser)->location);",
                f"{pad}            goto {array_fail};",
                f"{pad}        }}",
            ])
        length_limit = self._counter_limit(length_type_id)
        if length_limit is not None:
            lines.extend([
                f"{pad}        if ({variable}_count >= (size_t){length_limit}) {{",
                f"{pad}            jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {length_limit}, json_peek_token(parser)->location);",
                f"{pad}            goto {array_fail};",
                f"{pad}        }}",
            ])
        lines.extend([
            f"{pad}        if (!json_any_vec_reserve(parser->allocator, &{variable}_vec, sizeof({target.c_type}))) {{",
            f"{pad}            jbc_set_no_memory(parser);",
            f"{pad}            goto {array_fail};",
            f"{pad}        }}",
            f"{pad}        {target.c_type} *{variable}_element = ({target.c_type} *)({variable}_vec.data + {variable}_vec.byte_len);",
            f"{pad}        {variable}_vec.byte_len += sizeof({target.c_type});",
            f"{pad}        ++{variable}_count;",
        ])
        lines.extend(
            self._emit_decode_value(item.target, f"*{variable}_element", None, _Constraint(), array_fail, indent + 2, variable + "e")
        )
        lines.extend([
            f"{pad}        if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACKET) {{",
            f"{pad}            if (!json_array_try_end(parser)) goto {array_fail};",
            f"{pad}            break;",
            f"{pad}        }}",
            f"{pad}        if (!json_consume_comma(parser)) goto {array_fail};",
            f"{pad}    }}",
            f"{pad}    }}",
        ])
        lines.extend(self._emit_array_length_checks(f"{variable}_count", constraint, array_fail, indent + 1, variable))
        lines.extend([
            f"{pad}    {expression} = ({target.c_type} *){variable}_vec.data;",
            f"{pad}    {length_expression} = {variable}_count;",
            f"{pad}    {variable}_vec.data = NULL;",
            f"{pad}    goto {array_done};",
            f"{array_fail}:",
            f"{pad}    for (size_t {variable}_cleanup = 0; {variable}_cleanup < {variable}_count; ++{variable}_cleanup) {{",
        ])
        lines.extend(
            self._emit_release_value(
                item.target,
                f"(({target.c_type} *){variable}_vec.data)[{variable}_cleanup]",
                None,
                indent + 2,
                variable + "c",
                "parser->allocator",
            )
        )
        lines.extend([
            f"{pad}    }}",
            f"{pad}    if ({variable}_vec.data != NULL) parser->allocator->free({variable}_vec.data);",
            f"{pad}    goto {fail_label};",
            f"{array_done}: ;",
            f"{pad}}}",
        ])
        return lines

    def _generate_public_functions(self) -> list[str]:
        lines: list[str] = []
        functions = {item.name: item for item in self.schema.functions}
        for entry in self.decode_plan.entries:
            function = functions[entry.function_name]
            assert entry.record_id is not None
            output_type = function.parameter_types[1].strip()
            lines.extend([
                f"bool {function.name}(json_parser *parser, {output_type} out)",
                "{",
                "    if (parser == NULL || out == NULL) {",
                "        if (parser != NULL) json_set_error(parser, JSON_ERROR_OTHER_INVALID_STATE, NULL);",
                "        return false;",
                "    }",
                "    memset(out, 0, sizeof(*out));",
                f"    return {self._decode_name(entry.record_id)}(parser, out);",
                "}",
                "",
            ])
        for entry in self.release_plan.entries:
            function = functions[entry.function_name]
            assert entry.record_id is not None
            output_type = function.parameter_types[1].strip()
            lines.extend([
                f"void {function.name}(json_allocator *allocator, {output_type} out)",
                "{",
                "    if (allocator == NULL || out == NULL) return;",
                f"    {self._release_name(entry.record_id)}(allocator, out);",
                "}",
                "",
            ])
        return lines


def generate_c(schema: SchemaIR, decode_plan: DecodePlan, release_plan: ReleasePlan, include: str) -> str:
    return CGenerator(schema, decode_plan, release_plan).generate(include)
