from __future__ import annotations

import json
from dataclasses import dataclass

from .generate_plan import FieldPlan, GeneratePlan
from .schema import FieldSchema, RecordSchema, RecordShape, Schema, TypeKind


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


@dataclass(frozen=True)
class _Constraint:
    minimum: str | None = None
    maximum: str | None = None
    min_length: int | None = None
    max_length: int | None = None


class CGenerator:
    def __init__(self, schema: Schema, plan: GeneratePlan):
        self.schema = schema
        self.plan = plan
        self.types = schema.type_map()
        self.records = schema.record_map()
        self.fields = schema.field_map()
        self.type_plans = plan.type_map()

    def generate(self, include: str) -> str:
        self._validate_entrypoints()
        lines = [
            "/* Generated by annotation-parser. Do not edit. */",
            '#include "json_pull.h"',
            '#include "json_any_vec.h"',
            '#include "json_key_dispatch.h"',
            "#include <float.h>",
            "#include <stdbool.h>",
            "#include <stddef.h>",
            "#include <stdint.h>",
            "#include <string.h>",
            f"#include {_c_string(include)}",
            "",
        ]
        lines.extend(self._error_helpers())
        lines.append("")
        for record in self.schema.records:
            lines.append(self._release_prototype(record) + ";")
            lines.append(self._decode_prototype(record) + ";")
        lines.append("")
        for record in self.schema.records:
            lines.extend(self._generate_release(record))
            lines.append("")
        for record in self.schema.records:
            lines.extend(self._generate_decode(record))
            lines.append("")
        lines.extend(self._generate_public_functions())
        return "\n".join(lines).rstrip() + "\n"

    def _release_name(self, record_id: str) -> str:
        return self.type_plans[record_id].release_helper

    def _decode_name(self, record_id: str) -> str:
        return self.type_plans[record_id].decode_helper

    def _release_prototype(self, record: RecordSchema) -> str:
        return f"static void {self._release_name(record.id)}(json_allocator *allocator, {record.c_type} *out)"

    def _decode_prototype(self, record: RecordSchema) -> str:
        return f"static bool {self._decode_name(record.id)}(json_parser *parser, {record.c_type} *out)"

    def _validate_entrypoints(self) -> None:
        # Entrypoint signatures and target roles are validated while Schema is built.
        return

    def _error_helpers(self) -> list[str]:
        fields = [field for item in self.plan.types for field in item.fields]
        schema_fields = [self.fields[field.field_id] for field in fields]
        array_records = [
            self.records[item.record_id]
            for item in self.plan.types
            if item.shape is RecordShape.ARRAY
        ]
        used_types = {field.type_id for field in schema_fields}
        used_types.update(
            record.array.element_type_id
            for record in array_records
            if record.array is not None
        )
        pending = list(used_types)
        while pending:
            item = self.types[pending.pop()]
            if item.target is not None and item.target not in used_types:
                used_types.add(item.target)
                pending.append(item.target)
        needs_context = bool(fields)
        needs_length = any(
            self._counter_limit(
                self.fields[record.array.length_field_id].type_id
                if record.array and record.array.length_field_id
                else None
            )
            is not None
            or self._counter_limit(
                self.fields[record.array.capacity_field_id].type_id
                if record.array and record.array.capacity_field_id
                else None
            )
            is not None
            for record in array_records
        ) or any(
            field.min_length is not None
            or field.max_length is not None
            or self._counter_limit(
                self.fields[field.length_field_id].type_id
                if field.length_field_id
                else None
            )
            is not None
            or self.types[field.type_id].kind is TypeKind.FIXED_ARRAY
            or (
                self.types[field.type_id].kind is TypeKind.STRING
                and self.types[field.type_id].capacity is not None
            )
            for field in schema_fields
        )
        needs_number = any(
            field.minimum is not None or field.maximum is not None
            for field in schema_fields
        ) or any(
            self.types[type_id].kind is TypeKind.FLOAT and self.types[type_id].bits == 32
            for type_id in used_types
        )
        needs_memory = bool(array_records) or any(
            self.types[type_id].kind in {TypeKind.POINTER, TypeKind.DYNAMIC_ARRAY}
            or (
                self.types[type_id].kind is TypeKind.STRING
                and self.types[type_id].capacity is None
            )
            for type_id in used_types
        )

        lines: list[str] = []
        context = [
            "static inline void jbc_set_context_error(json_parser *parser, json_error_code code,",
            "                                  const char *key, json_source_location location)",
            "{",
            "    json_error_detail detail = {0};",
            "    detail.other.context.begin = key;",
            "    detail.other.context.end = key + strlen(key);",
            "    json_set_error_at(parser, code, &detail, location);",
            "}",
        ]
        length = [
            "static inline void jbc_set_length_error(json_parser *parser, json_error_code code,",
            "                                 json_range_target target, size_t limit,",
            "                                 json_source_location location)",
            "{",
            "    json_error_detail detail = {0};",
            "    detail.range.target = target;",
            "    detail.range.limit = limit;",
            "    json_set_error_at(parser, code, &detail, location);",
            "}",
        ]
        number = [
            "static inline void jbc_set_number_error(json_parser *parser, json_source_location location,",
            "                                 json_error_span value)",
            "{",
            "    json_error_detail detail = {0};",
            "    detail.range.target = JSON_RANGE_NUMBER_VALUE;",
            "    detail.range.value = value;",
            "    json_set_error_at(parser, JSON_ERROR_RANGE_NUMBER, &detail, location);",
            "}",
        ]
        memory = [
            "static inline void jbc_set_no_memory(json_parser *parser)",
            "{",
            "    json_set_error(parser, JSON_ERROR_OTHER_NO_MEMORY, NULL);",
            "}",
        ]
        for needed, chunk in (
            (needs_context, context),
            (needs_length, length),
            (needs_number, number),
            (needs_memory, memory),
        ):
            if needed:
                if lines:
                    lines.append("")
                lines.extend(chunk)
        return lines

    def _field_expression(self, path: tuple[str, ...], base: str = "out") -> str:
        return base + "->" + ".".join(path)

    def _field_schema(self, record: RecordSchema, path: tuple[str, ...]) -> FieldSchema:
        current = record
        result: FieldSchema | None = None
        for index, name in enumerate(path):
            result = next(field for field in current.fields if field.name == name)
            if index + 1 < len(path):
                current = self.records[result.type_id]
        assert result is not None
        return result

    def _generate_release(self, record: RecordSchema) -> list[str]:
        plan = self.type_plans[record.id]
        if record.shape is RecordShape.ARRAY:
            return self._generate_array_release(record)
        lines = [self._release_prototype(record), "{", "    if (out == NULL) {", "        return;", "    }"]
        for index, field_id in enumerate(plan.owned_field_ids):
            field = self.fields[field_id]
            expression = self._field_expression((field.name,))
            length_field = self.fields[field.length_field_id] if field.length_field_id else None
            length = self._field_expression((length_field.name,)) if length_field else None
            lines.extend(self._emit_release_value(field.type_id, expression, length, 1, f"r{index}"))
        lines.append("    memset(out, 0, sizeof(*out));")
        lines.append("}")
        return lines

    def _generate_array_release(self, record: RecordSchema) -> list[str]:
        layout = record.array
        assert layout is not None
        elems_field = self.fields[layout.elems_field_id]
        count_field_id = layout.length_field_id or layout.capacity_field_id
        elems = self._field_expression((elems_field.name,))
        lines = [
            self._release_prototype(record),
            "{",
            "    if (out == NULL) {",
            "        return;",
            "    }",
        ]
        if self.types[layout.element_type_id].owns_resources:
            assert count_field_id is not None
            count = self._field_expression((self.fields[count_field_id].name,))
            lines.extend([
                f"    if ({elems} != NULL) {{",
                f"        for (size_t r0 = 0; r0 < (size_t)({count}); ++r0) {{",
            ])
            lines.extend(
                self._emit_release_value(
                    layout.element_type_id, f"({elems})[r0]", None, 3, "r0e"
                )
            )
            lines.append("        }")
            lines.append("    }")
        lines.extend([
            f"    if ({elems} != NULL) {{",
            f"        allocator->free({elems});",
            "    }",
            "    memset(out, 0, sizeof(*out));",
            "}",
        ])
        return lines

    def _emit_release_value(
        self,
        type_id: str,
        expression: str,
        length_expression: str | None,
        indent: int,
        variable: str,
        allocator: str = "allocator",
    ) -> list[str]:
        item = self.types[type_id]
        pad = "    " * indent
        lines: list[str] = []
        if item.kind is TypeKind.STRING and item.capacity is None:
            lines.extend([
                f"{pad}if ({expression} != NULL) {{",
                f"{pad}    {allocator}->free({expression});",
                f"{pad}    {expression} = NULL;",
                f"{pad}}}",
            ])
        elif item.kind is TypeKind.RECORD:
            lines.append(f"{pad}{self._release_name(item.id)}({allocator}, &({expression}));")
        elif item.kind is TypeKind.POINTER and item.target is not None:
            lines.append(f"{pad}if ({expression} != NULL) {{")
            lines.extend(self._emit_release_value(item.target, f"*({expression})", None, indent + 1, variable + "p", allocator))
            lines.extend([
                f"{pad}    {allocator}->free({expression});",
                f"{pad}    {expression} = NULL;",
                f"{pad}}}",
            ])
        elif item.kind in {TypeKind.DYNAMIC_ARRAY, TypeKind.FIXED_ARRAY} and item.target is not None:
            if item.kind is TypeKind.DYNAMIC_ARRAY:
                assert length_expression is not None
                count = length_expression
            elif length_expression is not None:
                count = length_expression
            else:
                count = str(item.capacity or 0)
            lines.append(f"{pad}for (size_t {variable} = 0; {variable} < (size_t)({count}); ++{variable}) {{")
            lines.extend(
                self._emit_release_value(item.target, f"({expression})[{variable}]", None, indent + 1, variable + "e", allocator)
            )
            lines.append(f"{pad}}}")
            if item.kind is TypeKind.DYNAMIC_ARRAY:
                lines.extend([
                    f"{pad}if ({expression} != NULL) {{",
                    f"{pad}    {allocator}->free({expression});",
                    f"{pad}    {expression} = NULL;",
                    f"{pad}}}",
                ])
            if length_expression is not None:
                lines.append(f"{pad}{length_expression} = 0;")
        return lines

    def _generate_decode(self, record: RecordSchema) -> list[str]:
        plan = self.type_plans[record.id]
        if record.shape is RecordShape.ARRAY:
            return self._generate_array_decode(record)
        count = max(1, len(plan.fields))
        key_entries = plan.key_entries
        lines = [
            self._decode_prototype(record),
            "{",
        ]
        if key_entries:
            lines.extend([
                "    static const json_key_entry key_entries[] = {",
                *[
                    f"        {{{{{_c_string(entry.key)}, {len(entry.key.encode('utf-8'))}}}, {entry.field_index}}},"
                    for entry in key_entries
                ],
                "    };",
                "    static const json_key_map key_map = {key_entries, sizeof(key_entries) / sizeof(key_entries[0])};",
            ])
        else:
            lines.append("    static const json_key_map key_map = {NULL, 0};")
        lines.extend([
            f"    unsigned char seen[{count}] = {{0}};",
            "    json_source_location object_end_location = {0};",
            "    if (!json_object_begin(parser)) {",
            "        goto fail;",
            "    }",
            "    if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACE) {",
            "        object_end_location = json_peek_token(parser)->location;",
            "        if (!json_object_try_end(parser)) {",
            "            goto fail;",
            "        }",
            "        goto object_done;",
            "    }",
            "    while (true) {",
            "        json_source_location key_location = json_peek_token(parser)->location;",
            "        json_cow_str key = {0};",
            "        int field_index = -1;",
            "        if (!json_decode_string(parser, &key)) {",
            "            goto fail;",
            "        }",
            "        if (!json_consume_colon(parser)) {",
            "            json_free_cow_str(parser->allocator, &key);",
            "            goto fail;",
            "        }",
            "        json_slice key_slice = json_cow_str_as_slice(&key);",
            "        uint32_t dispatched_id = 0;",
            "        if (json_key_dispatch(&key_map, &key_slice, &dispatched_id)) {",
            "            field_index = (int)dispatched_id;",
            "        }",
            "        json_free_cow_str(parser->allocator, &key);",
            "        switch (field_index) {",
        ])
        for field in plan.fields:
            lines.extend(self._generate_field_case(record, field))
        lines.extend([
            "        default:",
            "            if (!json_skip_value(parser)) {",
            "                goto fail;",
            "            }",
            "            break;",
            "        }",
            "        if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACE) {",
            "            object_end_location = json_peek_token(parser)->location;",
            "            if (!json_object_try_end(parser)) {",
            "                goto fail;",
            "            }",
            "            break;",
            "        }",
            "        if (!json_consume_comma(parser)) {",
            "            goto fail;",
            "        }",
            "    }",
            "object_done:",
        ])
        for field in plan.fields:
            schema_field = self.fields[field.field_id]
            if schema_field.required:
                lines.extend([
                    f"    if (!seen[{field.seen_index}]) {{",
                    f"        jbc_set_context_error(parser, JSON_ERROR_OTHER_MISSING_REQUIRED_KEY, {_c_string(schema_field.key)}, object_end_location);",
                    "        goto fail;",
                    "    }",
                ])
        lines.extend([
            "    return true;",
            "fail:",
            f"    {self._release_name(record.id)}(parser->allocator, out);",
            "    return false;",
            "}",
        ])
        return lines

    def _counter_limit(self, type_id: str | None) -> int | None:
        if type_id is None:
            return None
        item = self.types[type_id]
        assert item.kind is TypeKind.INTEGER and not item.signed
        bits = item.bits or 64
        # The supported target is LP64, so a 64-bit unsigned counter can hold size_t.
        return (1 << bits) - 1 if bits < 64 else None

    def _emit_counter_check(
        self,
        value: str,
        type_id: str | None,
        location: str,
        fail_label: str,
        indent: int,
    ) -> list[str]:
        limit = self._counter_limit(type_id)
        if limit is None:
            return []
        pad = "    " * indent
        return [
            f"{pad}if ({value} > (size_t){limit}) {{",
            f"{pad}    jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {limit}, {location});",
            f"{pad}    goto {fail_label};",
            f"{pad}}}",
        ]

    def _generate_array_decode(self, record: RecordSchema) -> list[str]:
        layout = record.array
        assert layout is not None
        target = self.types[layout.element_type_id]
        elems_field = self.fields[layout.elems_field_id]
        length_field = self.fields[layout.length_field_id] if layout.length_field_id else None
        capacity_field = self.fields[layout.capacity_field_id] if layout.capacity_field_id else None
        elems = self._field_expression((elems_field.name,))
        length = self._field_expression((length_field.name,)) if length_field else None
        capacity = self._field_expression((capacity_field.name,)) if capacity_field else None
        length_type_id = length_field.type_id if length_field else None
        capacity_type_id = capacity_field.type_id if capacity_field else None
        lines = [
            self._decode_prototype(record),
            "{",
            "    json_any_vec array_vec = {0};",
            "    size_t array_count = 0;",
            f"    {elems} = NULL;",
        ]
        if self._counter_limit(capacity_type_id) is not None:
            lines.insert(4, "    json_source_location array_location = json_peek_token(parser)->location;")
        if length is not None:
            lines.append(f"    {length} = 0;")
        if capacity is not None:
            lines.append(f"    {capacity} = 0;")
        lines.extend([
            "    if (!json_array_begin(parser)) {",
            "        goto fail;",
            "    }",
            "    if (!json_array_try_end(parser)) {",
            "        while (true) {",
        ])
        # Reject before decoding the first element that cannot be represented by len.
        limit = self._counter_limit(length_type_id)
        if limit is not None:
            lines.extend([
                f"            if (array_count >= (size_t){limit}) {{",
                f"                jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {limit}, json_peek_token(parser)->location);",
                "                goto array_fail;",
                "            }",
            ])
        lines.extend([
            f"            if (!json_any_vec_reserve(parser->allocator, &array_vec, sizeof({target.c_type}))) {{",
            "                jbc_set_no_memory(parser);",
            "                goto array_fail;",
            "            }",
            f"            {target.c_type} *array_element = ({target.c_type} *)(array_vec.data + array_vec.byte_len);",
            f"            array_vec.byte_len += sizeof({target.c_type});",
            "            ++array_count;",
        ])
        lines.extend(
            self._emit_decode_value(
                layout.element_type_id,
                "*array_element",
                None,
                _Constraint(),
                "array_fail",
                3,
                "array_element",
            )
        )
        lines.extend([
            "            if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACKET) {",
            "                if (!json_array_try_end(parser)) goto array_fail;",
            "                break;",
            "            }",
            "            if (!json_consume_comma(parser)) goto array_fail;",
            "        }",
            "    }",
        ])
        if capacity is not None:
            lines.append(
                f"    size_t array_capacity = array_vec.byte_cap / sizeof({target.c_type});"
            )
            lines.extend(
                self._emit_counter_check(
                    "array_capacity", capacity_type_id, "array_location", "array_fail", 1
                )
            )
        lines.append(f"    {elems} = ({target.c_type} *)array_vec.data;")
        if length is not None:
            assert length_field is not None
            field_type = length_field.c_type
            lines.append(f"    {length} = ({field_type})array_count;")
        if capacity is not None:
            assert capacity_field is not None
            field_type = capacity_field.c_type
            lines.append(f"    {capacity} = ({field_type})array_capacity;")
        lines.extend([
            "    array_vec.data = NULL;",
            "    return true;",
            "array_fail:",
            "    for (size_t array_cleanup = 0; array_cleanup < array_count; ++array_cleanup) {",
        ])
        lines.extend(
            self._emit_release_value(
                layout.element_type_id,
                f"(({target.c_type} *)array_vec.data)[array_cleanup]",
                None,
                2,
                "array_cleanup_element",
                "parser->allocator",
            )
        )
        lines.extend([
            "    }",
            "    if (array_vec.data != NULL) parser->allocator->free(array_vec.data);",
            "fail:",
            f"    {self._release_name(record.id)}(parser->allocator, out);",
            "    return false;",
            "}",
        ])
        return lines

    def _generate_field_case(self, record: RecordSchema, field: FieldPlan) -> list[str]:
        schema_field = self.fields[field.field_id]
        index = field.seen_index
        expression = self._field_expression(field.path)
        length = self._field_expression(field.length_path) if field.length_path else None
        constraint = _Constraint(
            schema_field.minimum,
            schema_field.maximum,
            schema_field.min_length,
            schema_field.max_length,
        )
        lines = [f"        case {index}: {{"]
        lines.extend([
            f"            if (seen[{index}]) {{",
            f"                jbc_set_context_error(parser, JSON_ERROR_OTHER_DUPLICATE_KEY, {_c_string(schema_field.key)}, key_location);",
            "                goto fail;",
            "            }",
            f"            seen[{index}] = 1;",
        ])
        if schema_field.required:
            lines.extend([
                "            if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {",
                f"                jbc_set_context_error(parser, JSON_ERROR_OTHER_NULL_REQUIRED_VALUE, {_c_string(schema_field.key)}, json_peek_token(parser)->location);",
                "                goto fail;",
                "            }",
            ])
        lines.extend(
            self._emit_decode_value(
                schema_field.type_id,
                expression,
                length,
                constraint,
                "fail",
                3,
                f"f{index}",
                self._field_schema(record, field.length_path).type_id
                if field.length_path
                else None,
            )
        )
        lines.extend(["            break;", "        }"])
        return lines

    def _emit_decode_value(
        self,
        type_id: str,
        expression: str,
        length_expression: str | None,
        constraint: _Constraint,
        fail_label: str,
        indent: int,
        variable: str,
        length_type_id: str | None = None,
    ) -> list[str]:
        item = self.types[type_id]
        pad = "    " * indent
        lines: list[str] = []
        if item.kind is TypeKind.BOOL:
            lines.append(f"{pad}if (!json_decode_bool(parser, &({expression}))) goto {fail_label};")
        elif item.kind in {TypeKind.INTEGER, TypeKind.ENUM}:
            bits = item.bits or 32
            signed = bool(item.signed)
            function = f"json_decode_{'i' if signed else 'u'}{bits}"
            needs_location = constraint.minimum is not None or constraint.maximum is not None
            if item.kind is TypeKind.ENUM:
                temp_type = f"{'int' if signed else 'uint'}{bits}_t"
                lines.append(f"{pad}{temp_type} {variable}_number = 0;")
                if needs_location:
                    lines.append(f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
                    lines.append(f"{pad}json_error_span {variable}_span = {{json_peek_token(parser)->str.ptr, json_peek_token(parser)->str.ptr + json_peek_token(parser)->str.len}};")
                lines.append(f"{pad}if (!{function}(parser, &{variable}_number)) goto {fail_label};")
                lines.append(f"{pad}{expression} = ({item.c_type}){variable}_number;")
            else:
                if needs_location:
                    lines.append(f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
                    lines.append(f"{pad}json_error_span {variable}_span = {{json_peek_token(parser)->str.ptr, json_peek_token(parser)->str.ptr + json_peek_token(parser)->str.len}};")
                lines.append(f"{pad}if (!{function}(parser, &({expression}))) goto {fail_label};")
            lines.extend(self._emit_number_constraints(expression, constraint, variable, fail_label, indent))
        elif item.kind is TypeKind.FLOAT:
            needs_location = item.bits == 32 or constraint.minimum is not None or constraint.maximum is not None
            if needs_location:
                lines.append(f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
                lines.append(f"{pad}json_error_span {variable}_span = {{json_peek_token(parser)->str.ptr, json_peek_token(parser)->str.ptr + json_peek_token(parser)->str.len}};")
            if item.bits == 32:
                lines.append(f"{pad}double {variable}_number = 0.0;")
                lines.append(f"{pad}if (!json_decode_f64(parser, &{variable}_number)) goto {fail_label};")
                lines.append(f"{pad}if ({variable}_number < -FLT_MAX || {variable}_number > FLT_MAX) {{")
                lines.append(f"{pad}    jbc_set_number_error(parser, {variable}_location, {variable}_span);")
                lines.append(f"{pad}    goto {fail_label};")
                lines.append(f"{pad}}}")
                lines.append(f"{pad}{expression} = (float){variable}_number;")
            else:
                lines.append(f"{pad}if (!json_decode_f64(parser, &({expression}))) goto {fail_label};")
            lines.extend(self._emit_number_constraints(expression, constraint, variable, fail_label, indent))
        elif item.kind is TypeKind.STRING:
            lines.extend(self._emit_string(item, expression, constraint, fail_label, indent, variable))
        elif item.kind is TypeKind.RECORD:
            lines.append(f"{pad}if (!{self._decode_name(item.id)}(parser, &({expression}))) goto {fail_label};")
        elif item.kind is TypeKind.POINTER and item.target is not None:
            lines.extend(self._emit_pointer(item, expression, fail_label, indent, variable))
        elif item.kind is TypeKind.FIXED_ARRAY and item.target is not None:
            lines.extend(
                self._emit_fixed_array(
                    item,
                    expression,
                    length_expression,
                    length_type_id,
                    constraint,
                    fail_label,
                    indent,
                    variable,
                )
            )
        elif item.kind is TypeKind.DYNAMIC_ARRAY and item.target is not None:
            assert length_expression is not None
            lines.extend(
                self._emit_dynamic_array(
                    item,
                    expression,
                    length_expression,
                    length_type_id,
                    constraint,
                    fail_label,
                    indent,
                    variable,
                )
            )
        else:
            raise AssertionError(f"unsupported decode type {item}")
        return lines

    def _emit_number_constraints(
        self,
        expression: str,
        constraint: _Constraint,
        variable: str,
        fail_label: str,
        indent: int,
    ) -> list[str]:
        conditions = []
        if constraint.minimum is not None:
            conditions.append(f"({expression}) < ({constraint.minimum})")
        if constraint.maximum is not None:
            conditions.append(f"({expression}) > ({constraint.maximum})")
        if not conditions:
            return []
        pad = "    " * indent
        return [
            f"{pad}if ({' || '.join(conditions)}) {{",
            f"{pad}    jbc_set_number_error(parser, {variable}_location, {variable}_span);",
            f"{pad}    goto {fail_label};",
            f"{pad}}}",
        ]

    def _emit_string(self, item, expression, constraint, fail_label, indent, variable) -> list[str]:
        pad = "    " * indent
        lines: list[str] = []
        nullable = item.capacity is None
        if nullable:
            lines.extend([
                f"{pad}if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {{",
                f"{pad}    if (!json_decode_null(parser)) goto {fail_label};",
                f"{pad}}} else {{",
            ])
            body_indent = indent + 1
        else:
            body_indent = indent
        body = "    " * body_indent
        lines.extend([
            f"{body}json_source_location {variable}_location = json_peek_token(parser)->location;",
            f"{body}json_cow_str {variable}_string = {{0}};",
            f"{body}if (!json_decode_string(parser, &{variable}_string)) goto {fail_label};",
            f"{body}json_slice {variable}_slice = json_cow_str_as_slice(&{variable}_string);",
            f"{body}size_t {variable}_length = {variable}_slice.len;",
            f"{body}if (memchr({variable}_slice.ptr, '\\0', {variable}_length) != NULL) {{",
            f"{body}    json_free_cow_str(parser->allocator, &{variable}_string);",
            f"{body}    json_set_error_at(parser, JSON_ERROR_OTHER_EMBEDDED_NUL, NULL, {variable}_location);",
            f"{body}    goto {fail_label};",
            f"{body}}}",
        ])
        limits: list[tuple[str, int]] = []
        if constraint.min_length is not None:
            limits.append((f"{variable}_length < {constraint.min_length}", constraint.min_length))
        if constraint.max_length is not None:
            limits.append((f"{variable}_length > {constraint.max_length}", constraint.max_length))
        if item.capacity is not None:
            limits.append((f"{variable}_length >= {item.capacity}", max(0, item.capacity - 1)))
        for condition, limit in limits:
            lines.extend([
                f"{body}if ({condition}) {{",
                f"{body}    json_free_cow_str(parser->allocator, &{variable}_string);",
                f"{body}    jbc_set_length_error(parser, JSON_ERROR_RANGE_STRING_LENGTH, JSON_RANGE_STRING_LENGTH, {limit}, {variable}_location);",
                f"{body}    goto {fail_label};",
                f"{body}}}",
            ])
        if item.capacity is None:
            lines.extend([
                f"{body}json_error_code {variable}_code = json_cow_str_into_owned_c_str(parser->allocator, &{variable}_string, &({expression}));",
                f"{body}if ({variable}_code != JSON_ERROR_NONE) {{",
                f"{body}    json_free_cow_str(parser->allocator, &{variable}_string);",
                f"{body}    json_set_error_at(parser, {variable}_code, NULL, {variable}_location);",
                f"{body}    goto {fail_label};",
                f"{body}}}",
            ])
        else:
            lines.extend([
                f"{body}size_t {variable}_written = 0;",
                f"{body}(void)json_slice_write_to_buf(&{variable}_slice, {expression}, {item.capacity}, &{variable}_written);",
                f"{body}json_free_cow_str(parser->allocator, &{variable}_string);",
            ])
        if nullable:
            lines.append(f"{pad}}}")
        return lines

    def _emit_pointer(self, item, expression, fail_label, indent, variable) -> list[str]:
        pad = "    " * indent
        pointer_fail = f"{variable}_pointer_fail"
        pointer_done = f"{variable}_pointer_done"
        target = self.types[item.target]
        lines = [
            f"{pad}if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {{",
            f"{pad}    if (!json_decode_null(parser)) goto {fail_label};",
            f"{pad}}} else {{",
        ]
        if target.kind is TypeKind.RECORD:
            target_record = self.records[target.id]
            token = (
                "JSON_TOKEN_LBRACKET"
                if target_record.shape is RecordShape.ARRAY
                else "JSON_TOKEN_LBRACE"
            )
            expected = (
                "JSON_EXPECTED_ARRAY"
                if target_record.shape is RecordShape.ARRAY
                else "JSON_EXPECTED_OBJECT"
            )
            lines.extend([
                f"{pad}    if (json_peek_token(parser)->kind != {token}) {{",
                f"{pad}        json_error_detail {variable}_type_error = {{0}};",
                f"{pad}        {variable}_type_error.type.expected = {expected};",
                f"{pad}        {variable}_type_error.type.actual = json_peek_token(parser)->kind;",
                f"{pad}        json_set_error(parser, JSON_ERROR_TYPE_MISMATCH, &{variable}_type_error);",
                f"{pad}        goto {fail_label};",
                f"{pad}    }}",
            ])
        lines.extend([
            f"{pad}    {expression} = ({target.c_type} *)parser->allocator->malloc(sizeof(*({expression})));",
            f"{pad}    if ({expression} == NULL) {{",
            f"{pad}        jbc_set_no_memory(parser);",
            f"{pad}        goto {fail_label};",
            f"{pad}    }}",
            f"{pad}    memset({expression}, 0, sizeof(*({expression})));",
        ])
        lines.extend(self._emit_decode_value(item.target, f"*({expression})", None, _Constraint(), pointer_fail, indent + 1, variable + "p"))
        lines.extend([
            f"{pad}    goto {pointer_done};",
            f"{pointer_fail}:",
        ])
        lines.extend(self._emit_release_value(item.target, f"*({expression})", None, indent + 1, variable + "pr", "parser->allocator"))
        lines.extend([
            f"{pad}    parser->allocator->free({expression});",
            f"{pad}    {expression} = NULL;",
            f"{pad}    goto {fail_label};",
            f"{pointer_done}: ;",
            f"{pad}}}",
        ])
        return lines

    def _emit_array_length_checks(
        self, count: str, constraint: _Constraint, fail_label: str, indent: int, variable: str
    ) -> list[str]:
        pad = "    " * indent
        lines: list[str] = []
        for operator, limit in (("<", constraint.min_length), (">", constraint.max_length)):
            if limit is None:
                continue
            lines.extend([
                f"{pad}if ({count} {operator} {limit}) {{",
                f"{pad}    jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {limit}, {variable}_location);",
                f"{pad}    goto {fail_label};",
                f"{pad}}}",
            ])
        return lines

    def _emit_fixed_array(
        self,
        item,
        expression,
        length_expression,
        length_type_id,
        constraint,
        fail_label,
        indent,
        variable,
    ):
        pad = "    " * indent
        capacity = item.capacity or 0
        lines = [f"{pad}size_t {variable}_count = 0;"]
        if constraint.min_length is not None or constraint.max_length is not None:
            lines.insert(0, f"{pad}json_source_location {variable}_location = json_peek_token(parser)->location;")
        if length_expression:
            lines.append(f"{pad}{length_expression} = 0;")
        lines.extend([
            f"{pad}if (!json_array_begin(parser)) goto {fail_label};",
            f"{pad}if (!json_array_try_end(parser)) {{",
            f"{pad}while (true) {{",
            f"{pad}    if ({variable}_count >= {capacity}) {{",
            f"{pad}        jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {capacity}, json_peek_token(parser)->location);",
            f"{pad}        goto {fail_label};",
            f"{pad}    }}",
        ])
        if constraint.max_length is not None and constraint.max_length < capacity:
            lines.extend([
                f"{pad}    if ({variable}_count >= {constraint.max_length}) {{",
                f"{pad}        jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {constraint.max_length}, json_peek_token(parser)->location);",
                f"{pad}        goto {fail_label};",
                f"{pad}    }}",
            ])
        length_limit = self._counter_limit(length_type_id)
        if length_limit is not None:
            lines.extend([
                f"{pad}    if ({variable}_count >= (size_t){length_limit}) {{",
                f"{pad}        jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {length_limit}, json_peek_token(parser)->location);",
                f"{pad}        goto {fail_label};",
                f"{pad}    }}",
            ])
        if length_expression:
            # Include the zero-initialized current slot in rollback if element decoding fails.
            lines.extend([
                f"{pad}    ++{variable}_count;",
                f"{pad}    {length_expression} = {variable}_count;",
            ])
        lines.extend(
            self._emit_decode_value(
                item.target,
                (
                    f"({expression})[{variable}_count - 1]"
                    if length_expression
                    else f"({expression})[{variable}_count]"
                ),
                None,
                _Constraint(),
                fail_label,
                indent + 1,
                variable + "e",
            )
        )
        if not length_expression:
            lines.append(f"{pad}    ++{variable}_count;")
        lines.extend([
            f"{pad}    if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACKET) {{",
            f"{pad}        if (!json_array_try_end(parser)) goto {fail_label};",
            f"{pad}        break;",
            f"{pad}    }}",
            f"{pad}    if (!json_consume_comma(parser)) goto {fail_label};",
            f"{pad}}}",
            f"{pad}}}",
        ])
        lines.extend(self._emit_array_length_checks(f"{variable}_count", constraint, fail_label, indent, variable))
        return lines

    def _emit_dynamic_array(
        self,
        item,
        expression,
        length_expression,
        length_type_id,
        constraint,
        fail_label,
        indent,
        variable,
    ):
        pad = "    " * indent
        target = self.types[item.target]
        array_fail = f"{variable}_array_fail"
        array_done = f"{variable}_array_done"
        lines = [
            f"{pad}{expression} = NULL;",
            f"{pad}{length_expression} = 0;",
            f"{pad}if (json_peek_token(parser)->kind == JSON_TOKEN_NULL) {{",
            f"{pad}    if (!json_decode_null(parser)) goto {fail_label};",
            f"{pad}}} else {{",
            f"{pad}    json_any_vec {variable}_vec = {{0}};",
            f"{pad}    size_t {variable}_count = 0;",
            f"{pad}    if (!json_array_begin(parser)) goto {array_fail};",
            f"{pad}    if (!json_array_try_end(parser)) {{",
            f"{pad}    while (true) {{",
        ]
        if constraint.min_length is not None or constraint.max_length is not None:
            lines.insert(6, f"{pad}    json_source_location {variable}_location = json_peek_token(parser)->location;")
        if constraint.max_length is not None:
            lines.extend([
                f"{pad}        if ({variable}_count >= {constraint.max_length}) {{",
                f"{pad}            jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {constraint.max_length}, json_peek_token(parser)->location);",
                f"{pad}            goto {array_fail};",
                f"{pad}        }}",
            ])
        length_limit = self._counter_limit(length_type_id)
        if length_limit is not None:
            lines.extend([
                f"{pad}        if ({variable}_count >= (size_t){length_limit}) {{",
                f"{pad}            jbc_set_length_error(parser, JSON_ERROR_RANGE_ARRAY_LENGTH, JSON_RANGE_ARRAY_LENGTH, {length_limit}, json_peek_token(parser)->location);",
                f"{pad}            goto {array_fail};",
                f"{pad}        }}",
            ])
        lines.extend([
            f"{pad}        if (!json_any_vec_reserve(parser->allocator, &{variable}_vec, sizeof({target.c_type}))) {{",
            f"{pad}            jbc_set_no_memory(parser);",
            f"{pad}            goto {array_fail};",
            f"{pad}        }}",
            f"{pad}        {target.c_type} *{variable}_element = ({target.c_type} *)({variable}_vec.data + {variable}_vec.byte_len);",
            f"{pad}        {variable}_vec.byte_len += sizeof({target.c_type});",
            f"{pad}        ++{variable}_count;",
        ])
        lines.extend(
            self._emit_decode_value(item.target, f"*{variable}_element", None, _Constraint(), array_fail, indent + 2, variable + "e")
        )
        lines.extend([
            f"{pad}        if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACKET) {{",
            f"{pad}            if (!json_array_try_end(parser)) goto {array_fail};",
            f"{pad}            break;",
            f"{pad}        }}",
            f"{pad}        if (!json_consume_comma(parser)) goto {array_fail};",
            f"{pad}    }}",
            f"{pad}    }}",
        ])
        lines.extend(self._emit_array_length_checks(f"{variable}_count", constraint, array_fail, indent + 1, variable))
        lines.extend([
            f"{pad}    {expression} = ({target.c_type} *){variable}_vec.data;",
            f"{pad}    {length_expression} = {variable}_count;",
            f"{pad}    {variable}_vec.data = NULL;",
            f"{pad}    goto {array_done};",
            f"{array_fail}:",
            f"{pad}    for (size_t {variable}_cleanup = 0; {variable}_cleanup < {variable}_count; ++{variable}_cleanup) {{",
        ])
        lines.extend(
            self._emit_release_value(
                item.target,
                f"(({target.c_type} *){variable}_vec.data)[{variable}_cleanup]",
                None,
                indent + 2,
                variable + "c",
                "parser->allocator",
            )
        )
        lines.extend([
            f"{pad}    }}",
            f"{pad}    if ({variable}_vec.data != NULL) parser->allocator->free({variable}_vec.data);",
            f"{pad}    goto {fail_label};",
            f"{array_done}: ;",
            f"{pad}}}",
        ])
        return lines

    def _generate_public_functions(self) -> list[str]:
        lines: list[str] = []
        for function in self.schema.functions:
            if function.role != "jsonDecode":
                continue
            output_type = function.parameter_c_types[1].strip()
            lines.extend([
                f"bool {function.name}(json_parser *parser, {output_type} out)",
                "{",
                "    if (parser == NULL || out == NULL) {",
                "        if (parser != NULL) json_set_error(parser, JSON_ERROR_OTHER_INVALID_STATE, NULL);",
                "        return false;",
                "    }",
                "    memset(out, 0, sizeof(*out));",
                f"    return {self._decode_name(function.record_id)}(parser, out);",
                "}",
                "",
            ])
        for function in self.schema.functions:
            if function.role != "jsonCleanup":
                continue
            output_type = function.parameter_c_types[1].strip()
            lines.extend([
                f"void {function.name}(json_allocator *allocator, {output_type} out)",
                "{",
                "    if (allocator == NULL || out == NULL) return;",
                f"    {self._release_name(function.record_id)}(allocator, out);",
                "}",
                "",
            ])
        return lines


def generate_c(schema: Schema, plan: GeneratePlan, include: str) -> str:
    return CGenerator(schema, plan).generate(include)
