from __future__ import annotations

from string import Template

C_FILE = r"""
/* Generated by annotation-parser. Do not edit. */
#include "json_pull.h"
#include "json_any_vec.h"
#include "json_key_dispatch.h"
#include <float.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include $include

$error_helpers

$prototypes

$release_functions

$field_decode_functions

$decode_functions

$public_functions
"""


ERROR_HELPERS = r"""
$context
$length
$number
$memory
"""


ERROR_HELPER_FRAGMENTS = {
    "context": r"""
static inline void jbc_set_context_error(
    json_parser *parser,
    json_error_code code,
    const char *key,
    json_source_location location
)
{
    json_error_detail detail = {0};
    detail.other.context.begin = key;
    detail.other.context.end = key + strlen(key);
    json_set_error_at(parser, code, &detail, location);
}
""",
    "length": r"""
static inline void jbc_set_length_error(
    json_parser *parser,
    json_error_code code,
    json_range_target target,
    size_t limit,
    json_source_location location
)
{
    json_error_detail detail = {0};
    detail.range.target = target;
    detail.range.limit = limit;
    json_set_error_at(parser, code, &detail, location);
}
""",
    "number": r"""
static inline void jbc_set_number_error(
    json_parser *parser,
    json_source_location location,
    json_error_span value
)
{
    json_error_detail detail = {0};
    detail.range.target = JSON_RANGE_NUMBER_VALUE;
    detail.range.value = value;
    json_set_error_at(parser, JSON_ERROR_RANGE_NUMBER, &detail, location);
}
""",
    "memory": r"""
static inline void jbc_set_no_memory(json_parser *parser)
{
    json_set_error(parser, JSON_ERROR_OTHER_NO_MEMORY, NULL);
}
""",
}


KEY_MAP = r"""
$entry_declaration
static const json_key_map $map_name = {
    $entry_pointer,
    $entry_count,
};
$primary_key_declaration
"""


OBJECT_DECODE = r"""
$key_map

$prototype
{
    unsigned char seen[$seen_count] = {0};
    json_source_location object_end_location = {0};

    if (!json_object_begin(parser)) {
        goto fail;
    }
    if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACE) {
        object_end_location = json_peek_token(parser)->location;
        if (!json_object_try_end(parser)) {
            goto fail;
        }
        goto object_done;
    }

    while (true) {
        json_source_location key_location = json_peek_token(parser)->location;
        json_cow_str key = {0};

        if (!json_decode_string(parser, &key)) {
            goto fail;
        }
        if (!json_consume_colon(parser)) {
            json_free_cow_str(parser->allocator, &key);
            goto fail;
        }

        json_slice key_slice = json_cow_str_as_slice(&key);
        const json_key_entry *entry = json_key_dispatch(&$map_name, &key_slice);
        json_free_cow_str(parser->allocator, &key);

        if (entry == NULL) {
            if (!json_skip_value(parser)) {
                goto fail;
            }
        } else {
            if (seen[entry->id]) {
                jbc_set_context_error(
                    parser,
                    JSON_ERROR_OTHER_DUPLICATE_KEY,
                    $primary_keys_name[entry->id],
                    key_location
                );
                goto fail;
            }
            seen[entry->id] = 1;
            if (!entry->decode(parser, out)) {
                goto fail;
            }
        }

        if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACE) {
            object_end_location = json_peek_token(parser)->location;
            if (!json_object_try_end(parser)) {
                goto fail;
            }
            break;
        }
        if (!json_consume_comma(parser)) {
            goto fail;
        }
    }

object_done:
$required_checks
    return true;

fail:
    $rollback_helper(parser->allocator, out);
    return false;
}
"""


OBJECT_FIELD_DECODE = r"""
$prototype
{
    $object_type *out = ($object_type *)object;
$body
    return true;

fail:
    return false;
}
"""


ARRAY_RECORD_DECODE = r"""
$prototype
{
    json_any_vec array_vec = {0};
    size_t array_count = 0;
$location_declaration
    $elems = NULL;
$length_init
$capacity_init

    if (!json_array_begin(parser)) {
        goto fail;
    }
    if (!json_array_try_end(parser)) {
        while (true) {
$length_guard
            if (!json_any_vec_reserve(parser->allocator, &array_vec, sizeof($element_type))) {
                jbc_set_no_memory(parser);
                goto array_fail;
            }
            $element_type *array_element =
                ($element_type *)(array_vec.data + array_vec.byte_len);
            array_vec.byte_len += sizeof($element_type);
            ++array_count;
$decode_element
            if (json_peek_token(parser)->kind == JSON_TOKEN_RBRACKET) {
                if (!json_array_try_end(parser)) {
                    goto array_fail;
                }
                break;
            }
            if (!json_consume_comma(parser)) {
                goto array_fail;
            }
        }
    }
$capacity_result
    $elems = ($element_type *)array_vec.data;
$length_result
$capacity_assignment
    array_vec.data = NULL;
    return true;

array_fail:
    for (size_t array_cleanup = 0; array_cleanup < array_count; ++array_cleanup) {
$release_element
    }
    if (array_vec.data != NULL) {
        parser->allocator->free(array_vec.data);
    }
fail:
    $rollback_helper(parser->allocator, out);
    return false;
}
"""


OBJECT_RELEASE = r"""
$prototype
{
    if (out == NULL) {
        return;
    }
$body
    memset(out, 0, sizeof(*out));
}
"""


ARRAY_RECORD_RELEASE = r"""
$prototype
{
    if (out == NULL) {
        return;
    }
$element_release
    if ($elems != NULL) {
        allocator->free($elems);
    }
    memset(out, 0, sizeof(*out));
}
"""


PUBLIC_DECODE = r"""
bool $function(json_parser *parser, $output_type out)
{
    if (parser == NULL || out == NULL) {
        if (parser != NULL) {
            json_set_error(parser, JSON_ERROR_OTHER_INVALID_STATE, NULL);
        }
        return false;
    }
    memset(out, 0, sizeof(*out));
    return $decode_helper(parser, out);
}
"""


PUBLIC_CLEANUP = r"""
void $function(json_allocator *allocator, $output_type out)
{
    if (allocator == NULL || out == NULL) {
        return;
    }
    $release_helper(allocator, out);
}
"""


C_TEMPLATES = (
    C_FILE,
    ERROR_HELPERS,
    KEY_MAP,
    OBJECT_DECODE,
    OBJECT_FIELD_DECODE,
    ARRAY_RECORD_DECODE,
    OBJECT_RELEASE,
    ARRAY_RECORD_RELEASE,
    PUBLIC_DECODE,
    PUBLIC_CLEANUP,
)


def render_c_template(template: str, **values: str) -> str:
    expected = set(Template(template).get_identifiers())
    provided = set(values)
    if missing := expected - provided:
        raise ValueError(f"missing C template values: {', '.join(sorted(missing))}")
    if extra := provided - expected:
        raise ValueError(f"unused C template values: {', '.join(sorted(extra))}")
    return Template(template).substitute(values).strip("\n")
