from __future__ import annotations

from string import Template

C_FILE = r"""
/* Generated by annotation-parser. Do not edit. */
#include "json_reflect.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include $include

$forward_declarations

$descriptors

$public_functions
"""

FORWARD_DECLARATIONS = r"""
$type_declarations
$record_declarations
"""

DESCRIPTOR_BLOCK = r"""
$constraints
$keys
$fields
$storage
$array_layout
$record
$type
"""

PUBLIC_DECODE = r"""
bool $function(json_parser *parser, $output_type out)
{
    if (parser == NULL || out == NULL) {
        if (parser != NULL) {
            json_set_error(parser, JSON_ERROR_OTHER_INVALID_STATE, NULL);
        }
        return false;
    }
    memset(out, 0, sizeof(*out));
    return json_reflect_decode(parser, &$descriptor, out);
}
"""

PUBLIC_CLEANUP = r"""
void $function(json_allocator *allocator, $output_type out)
{
    if (allocator == NULL || out == NULL) {
        return;
    }
    json_reflect_release(allocator, &$descriptor, out);
}
"""

C_TEMPLATES = (
    C_FILE,
    FORWARD_DECLARATIONS,
    DESCRIPTOR_BLOCK,
    PUBLIC_DECODE,
    PUBLIC_CLEANUP,
)


def render_c_template(template: str, **values: str) -> str:
    expected = set(Template(template).get_identifiers())
    provided = set(values)
    if missing := expected - provided:
        raise ValueError(f"missing C template values: {', '.join(sorted(missing))}")
    if extra := provided - expected:
        raise ValueError(f"unused C template values: {', '.join(sorted(extra))}")
    return Template(template).substitute(values).strip("\n")
