/* Generated by annotation-parser. Do not edit. */
#include "json_reflect.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include "model.h"

static const json_reflect_type jbc_type_dynamic_array_record_Child;
static const json_reflect_type jbc_type_enum_Kind;
static const json_reflect_type jbc_type_fixed_array_3_integer_i32;
static const json_reflect_type jbc_type_integer_i32;
static const json_reflect_type jbc_type_integer_u64;
static const json_reflect_type jbc_type_pointer_record_Child;
static const json_reflect_type jbc_type_Child;
static const json_reflect_type jbc_type_Root;
static const json_reflect_type jbc_type_string_fixed_16;
static const json_reflect_type jbc_type_string_pointer;
static const json_reflect_record jbc_record_Child;
static const json_reflect_record jbc_record_Root;

static const json_reflect_type jbc_type_dynamic_array_record_Child = {
    .kind = JSON_REFLECT_DYNAMIC_ARRAY,
    .bits = 0,
    .flags = 0,
    .size = sizeof(Child *),
    .capacity = 0,
    .target = &jbc_type_Child,
    .record = NULL,
};

static const json_reflect_type jbc_type_enum_Kind = {
    .kind = JSON_REFLECT_ENUM,
    .bits = 32,
    .flags = JSON_REFLECT_SIGNED,
    .size = sizeof(Kind),
    .capacity = 0,
    .target = NULL,
    .record = NULL,
};

static const json_reflect_type jbc_type_fixed_array_3_integer_i32 = {
    .kind = JSON_REFLECT_FIXED_ARRAY,
    .bits = 0,
    .flags = 0,
    .size = sizeof(int[3]),
    .capacity = 3,
    .target = &jbc_type_integer_i32,
    .record = NULL,
};

static const json_reflect_type jbc_type_integer_i32 = {
    .kind = JSON_REFLECT_INTEGER,
    .bits = 32,
    .flags = JSON_REFLECT_SIGNED,
    .size = sizeof(int),
    .capacity = 0,
    .target = NULL,
    .record = NULL,
};

static const json_reflect_type jbc_type_integer_u64 = {
    .kind = JSON_REFLECT_INTEGER,
    .bits = 64,
    .flags = 0,
    .size = sizeof(size_t),
    .capacity = 0,
    .target = NULL,
    .record = NULL,
};

static const json_reflect_type jbc_type_pointer_record_Child = {
    .kind = JSON_REFLECT_POINTER,
    .bits = 0,
    .flags = 0,
    .size = sizeof(Child *),
    .capacity = 0,
    .target = &jbc_type_Child,
    .record = NULL,
};

static const json_reflect_type jbc_type_string_fixed_16 = {
    .kind = JSON_REFLECT_STRING,
    .bits = 0,
    .flags = 0,
    .size = sizeof(char[16]),
    .capacity = 16,
    .target = NULL,
    .record = NULL,
};

static const json_reflect_type jbc_type_string_pointer = {
    .kind = JSON_REFLECT_STRING,
    .bits = 0,
    .flags = 0,
    .size = sizeof(char *),
    .capacity = 0,
    .target = NULL,
    .record = NULL,
};

static const json_key_entry jbc_record_Child_keys[] = {
    {{"label", sizeof("label") - 1}, 0},
};
static const json_reflect_field jbc_record_Child_fields[] = {
    {
        .primary_key = {"label", sizeof("label") - 1},
        .offset = offsetof(struct Child, label),
        .type = &jbc_type_string_pointer,
        .constraints = NULL,
        .count_offset = SIZE_MAX,
        .count_type = NULL,
        .flags = JSON_REFLECT_REQUIRED,
    },
};
static const json_reflect_storage jbc_record_Child_storage[] = {
    {
        .offset = offsetof(struct Child, label),
        .type = &jbc_type_string_pointer,
        .count_offset = SIZE_MAX,
        .count_type = NULL,
    },
};

static const json_reflect_record jbc_record_Child = {
    .shape = JSON_REFLECT_OBJECT,
    .size = sizeof(struct Child),
    .keys = {jbc_record_Child_keys, sizeof(jbc_record_Child_keys) / sizeof(jbc_record_Child_keys[0])},
    .fields = jbc_record_Child_fields,
    .field_count = sizeof(jbc_record_Child_fields) / sizeof(jbc_record_Child_fields[0]),
    .storage = jbc_record_Child_storage,
    .storage_count = sizeof(jbc_record_Child_storage) / sizeof(jbc_record_Child_storage[0]),
    .array = NULL,
};
static const json_reflect_type jbc_type_Child = {
    .kind = JSON_REFLECT_RECORD,
    .bits = 0,
    .flags = 0,
    .size = sizeof(struct Child),
    .capacity = 0,
    .target = NULL,
    .record = &jbc_record_Child,
};

static const json_reflect_constraints jbc_record_Root_field_0_constraints = {
    .flags = JSON_REFLECT_HAS_MIN,
    .minimum = {.signed_value = 1},
    .maximum = {0},
    .min_length = 0,
    .max_length = 0,
};
static const json_reflect_constraints jbc_record_Root_field_1_constraints = {
    .flags = JSON_REFLECT_HAS_MAX_LENGTH,
    .minimum = {0},
    .maximum = {0},
    .min_length = 0,
    .max_length = 12,
};
static const json_reflect_constraints jbc_record_Root_field_2_constraints = {
    .flags = JSON_REFLECT_HAS_MAX_LENGTH,
    .minimum = {0},
    .maximum = {0},
    .min_length = 0,
    .max_length = 4,
};
static const json_key_entry jbc_record_Root_keys[] = {
    {{"id", sizeof("id") - 1}, 0},
    {{"kind", sizeof("kind") - 1}, 5},
    {{"name", sizeof("name") - 1}, 1},
    {{"values", sizeof("values") - 1}, 3},
    {{"children", sizeof("children") - 1}, 2},
    {{"optional", sizeof("optional") - 1}, 4},
    {{"identifier", sizeof("identifier") - 1}, 0},
};
static const json_reflect_field jbc_record_Root_fields[] = {
    {
        .primary_key = {"identifier", sizeof("identifier") - 1},
        .offset = offsetof(struct Root, id),
        .type = &jbc_type_integer_i32,
        .constraints = &jbc_record_Root_field_0_constraints,
        .count_offset = SIZE_MAX,
        .count_type = NULL,
        .flags = JSON_REFLECT_REQUIRED,
    },
    {
        .primary_key = {"name", sizeof("name") - 1},
        .offset = offsetof(struct Root, name),
        .type = &jbc_type_string_fixed_16,
        .constraints = &jbc_record_Root_field_1_constraints,
        .count_offset = SIZE_MAX,
        .count_type = NULL,
        .flags = 0,
    },
    {
        .primary_key = {"children", sizeof("children") - 1},
        .offset = offsetof(struct Root, children),
        .type = &jbc_type_dynamic_array_record_Child,
        .constraints = &jbc_record_Root_field_2_constraints,
        .count_offset = offsetof(struct Root, childCount),
        .count_type = &jbc_type_integer_u64,
        .flags = 0,
    },
    {
        .primary_key = {"values", sizeof("values") - 1},
        .offset = offsetof(struct Root, values),
        .type = &jbc_type_fixed_array_3_integer_i32,
        .constraints = NULL,
        .count_offset = offsetof(struct Root, valueCount),
        .count_type = &jbc_type_integer_u64,
        .flags = 0,
    },
    {
        .primary_key = {"optional", sizeof("optional") - 1},
        .offset = offsetof(struct Root, optional),
        .type = &jbc_type_pointer_record_Child,
        .constraints = NULL,
        .count_offset = SIZE_MAX,
        .count_type = NULL,
        .flags = 0,
    },
    {
        .primary_key = {"kind", sizeof("kind") - 1},
        .offset = offsetof(struct Root, kind),
        .type = &jbc_type_enum_Kind,
        .constraints = NULL,
        .count_offset = SIZE_MAX,
        .count_type = NULL,
        .flags = 0,
    },
};
static const json_reflect_storage jbc_record_Root_storage[] = {
    {
        .offset = offsetof(struct Root, children),
        .type = &jbc_type_dynamic_array_record_Child,
        .count_offset = offsetof(struct Root, childCount),
        .count_type = &jbc_type_integer_u64,
    },
    {
        .offset = offsetof(struct Root, optional),
        .type = &jbc_type_pointer_record_Child,
        .count_offset = SIZE_MAX,
        .count_type = NULL,
    },
};

static const json_reflect_record jbc_record_Root = {
    .shape = JSON_REFLECT_OBJECT,
    .size = sizeof(struct Root),
    .keys = {jbc_record_Root_keys, sizeof(jbc_record_Root_keys) / sizeof(jbc_record_Root_keys[0])},
    .fields = jbc_record_Root_fields,
    .field_count = sizeof(jbc_record_Root_fields) / sizeof(jbc_record_Root_fields[0]),
    .storage = jbc_record_Root_storage,
    .storage_count = sizeof(jbc_record_Root_storage) / sizeof(jbc_record_Root_storage[0]),
    .array = NULL,
};
static const json_reflect_type jbc_type_Root = {
    .kind = JSON_REFLECT_RECORD,
    .bits = 0,
    .flags = 0,
    .size = sizeof(struct Root),
    .capacity = 0,
    .target = NULL,
    .record = &jbc_record_Root,
};

void releaseRoot(json_allocator *allocator, Root * out)
{
    if (allocator == NULL || out == NULL) {
        return;
    }
    json_reflect_release(allocator, &jbc_type_Root, out);
}

bool decodeRoot(json_parser *parser, Root * out)
{
    if (parser == NULL || out == NULL) {
        if (parser != NULL) {
            json_set_error(parser, JSON_ERROR_OTHER_INVALID_STATE, NULL);
        }
        return false;
    }
    memset(out, 0, sizeof(*out));
    return json_reflect_decode(parser, &jbc_type_Root, out);
}
